runtime: java11
instance_class: F2
env: standard

automatic_scaling:
  target_cpu_utilization: 0.65

env_variables:
  SPRING_PROFILES_ACTIVE: "cloud"
  SPRING_DATASOURCE_URL: "jdbc:mysql://google/milktea?useSSL=false&cloudSqlInstance=milkteacloud-408611:us-central1:milkteacloud&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=root&password="
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"